scripts:
  - name: ScriptBaseClass
    send_args: false # default true
  - name: setupAnonymousAccess
  - name: setupRealms
  - name: syncCleanupPolicies
  - name: syncContentSelectors
  - name: syncRoutingRules
  - name: syncCustomPrivileges
  - name: syncCustomRoles
  - name: syncCustomLocalUsers
  - name: syncBlobStores
  - name: syncRepositories
  - name: setupBaseUrl
  - name: setupHttpProxy
  - name: syncScheduledTasks
  - name: syncTrustStore
  - name: setupEmailServer
  - name: syncLdapConnections
  - name: syncCustomLdapUsers
  - name: setupAdminPassword
